name: TreeMe
version: 1.0.0
author: "Jonah Alligood"
main: me.jonahisadev.treeme.Main
api-version: 1.16
website: "https://github.com/jonahisadev/TreeMe"

commands:
  treeme:
    description: Control personal usage of TreeMe
    aliases: [tree]
    usage: "/treeme help"